create table CIM_EnabledLogicalElement (id number(19,0) not null, EnabledState number(10,0), OtherEnabledState varchar2(3000), RequestedState number(10,0), EnabledDefault number(10,0), TimeOfLastStateChange timestamp, primary key (id));
create table CIM_LogicalElement (id number(19,0) not null, primary key (id));
create table CIM_ManagedElement (id number(19,0) not null, discriminator_type varchar2(255 char) not null, Caption varchar2(3000), Description varchar2(3000), ElementName varchar2(3000), class_type varchar2(255 char), namespace_path varchar2(255 char), primary key (id));
create table CIM_ManagedSystemElement (id number(19,0) not null, InstallDate timestamp, Name varchar2(3000), OperationalStatus_value varchar2(4000 char), OperationalStatus_value_type number(10,0), StatusDescriptions_value varchar2(4000 char), StatusDescriptions_value_type number(10,0), primary key (id));
create table CIM_Service (id number(19,0) not null, SystemCreationClassName varchar2(3000), SystemName varchar2(3000), CreationClassName varchar2(3000), PrimaryOwnerName varchar2(3000), PrimaryOwnerContact varchar2(3000), Started number(1,0), primary key (id));
create table CIM_WBEMService (id number(19,0) not null, primary key (id));
create table HNSD_GDEpriT861Provider (id number(19,0) not null, primary key (id));
create table HNSD_GenericAgentProvider (id number(19,0) not null, CustomAgentVendor varchar2(3000), CustomAgentName varchar2(3000), DeviceClassName varchar2(3000), MonitoringInterfaceClass varchar2(3000), primary key (id));
create table HNSD_GenericProvider (id number(19,0) not null, DeviceDefaultVersion varchar2(3000), DeviceVersionOID varchar2(3000), DeviceSysObjectID varchar2(3000), primary key (id));
create table HNSD_Provider (id number(19,0) not null, AutoStart number(1,0), ServerId varchar2(3000), primary key (id));
create table UIM_AutonomousDeviceInstantiat (id number(19,0) not null, Version varchar2(3000), LogFileEnabled number(1,0), LogLevel number(10,0), LogConsoleEnabled number(1,0), LogDirectory varchar2(3000), AutoStart number(1,0), primary key (id));
create table UIM_AutonomousNetworkResourceI (id number(19,0) not null, UniqueName varchar2(3000), primary key (id));
create table UIM_GDEpriT861EthernetGrouping (id number(19,0) not null, Diagramm number(1,0), primary key (id));
create table UIM_GDEpriT861EthernetPort (id number(19,0) not null, MTU number(10,0), PortSpeed number(19,2), PhysicalAddress varchar2(3000), AdminStatus number(10,0), OperStatus number(10,0), LastChange varchar2(3000), InOctets number(19,2), InUcastPkts number(19,2), InNUcastPkts number(19,2), InDiscards number(19,2), InErrors number(19,2), InUnknownProtos number(19,2), OutOctets number(19,2), OutUcastPkts number(19,2), OutNUcastPkts number(19,2), OutDiscards number(19,2), OutErrors number(19,2), OutQLen number(19,2), Alias varchar2(3000), Diagramm number(1,0), primary key (id));
create table UIM_GDEpriT861InstComponent (id number(19,0) not null, CustomAgentHome varchar2(3000), CustomAgentName varchar2(3000), CustomAgentVendor varchar2(3000), ElementType varchar2(3000), Script varchar2(3000), primary key (id));
create table UIM_GDEpriT861MgmtInterface (id number(19,0) not null, primary key (id));
create table UIM_GDEpriT861MonInterface (id number(19,0) not null, PerformancePollingTime number(10,0), PerformancePollingFrequency varchar2(3000), primary key (id));
create table UIM_GDEpriT861NetworkElement (id number(19,0) not null, Script varchar2(3000), SystemUpTimeTxt varchar2(3000), HardwareVersion varchar2(3000), SoftwareVersion varchar2(3000), StackFlag number(10,0), BootImgPrimary varchar2(3000), BootImgSecondary varchar2(3000), BootStartUpCfg varchar2(3000), StartUpStatus number(10,0), NumberOfPorts number(10,0), Diagramm number(1,0), primary key (id));
create table UIM_GDEpriT861Port (id number(19,0) not null, Diagramm number(1,0), LinkStatus number(10,0), DuplexStatus number(10,0), PortSpeed number(10,0), PortMedia number(10,0), MediaMode number(10,0), SpeedMode number(10,0), DuplexMode number(10,0), PortDisable number(10,0), FlowCtrl number(10,0), EgressRate number(10,0), PackType number(10,0), LowProbandwidth number(10,0), NormalProbandwidth number(10,0), MediumProbandwidth number(10,0), HighProbandwidth number(10,0), PortType number(10,0), PortVID number(10,0), InGoodOctets number(19,2), InBadOctets number(19,2), InUnicasts number(19,2), InBroadCasts number(19,2), InMultiCasts number(19,2), InPause number(19,2), InUndersize number(19,2), InFragments number(19,2), InOversize number(19,2), InJabber number(19,2), InRxErr number(19,2), InFCSErr number(19,2), OutOctets number(19,2), OutUnicast number(19,2), OutBroadCasts number(19,2), OutMulticasts number(19,2), OutPause number(19,2), Excessive number(19,2), Collisions number(19,2), Deferred number(19,2), Single number(19,2), Multple number(19,2), Late number(19,2), primary key (id));
create table UIM_GDEpriT861Vlans (id number(19,0) not null, PortVlanID number(10,0), PortMember number(19,2), PortVlanStatus number(10,0), primary key (id));
create table UIM_GDEpriT861VlansGrouping (id number(19,0) not null, Diagramm number(1,0), primary key (id));
create table UIM_GenericAgentMonInterface (id number(19,0) not null, AlertSeverityLevel number(10,0), AgentHome varchar2(3000), SystemName varchar2(3000), LogFileEnabled number(1,0), LogLevel number(10,0), LogConsoleEnabled number(1,0), LogDirectory varchar2(3000), primary key (id));
create table UIM_GenericDeviceInstComponent (id number(19,0) not null, StatusSleep number(19,0), AlertSeverityLevel number(10,0), primary key (id));
create table UIM_GenericDeviceMonInterface (id number(19,0) not null, StatusSleep number(19,0), CheckConnectionTimeStamp timestamp, primary key (id));
create table UIM_GenericGrouping (id number(19,0) not null, primary key (id));
create table UIM_GenericLogicalDevice (id number(19,0) not null, primary key (id));
create table UIM_GenericNetworkElement (id number(19,0) not null, SystemUpTime number(19,0), SystemLocation varchar2(3000), SystemContact varchar2(3000), SnmpSleepTimeout number(10,0), DeviceName varchar2(3000), IsElementInEMS number(1,0), primary key (id));
create table UIM_GenericPort (id number(19,0) not null, primary key (id));
create table UIM_GenericSNMPDeviceMonInterf (id number(19,0) not null, CustomAgentHome varchar2(3000), CustomAgentName varchar2(3000), CustomAgentVendor varchar2(3000), primary key (id));
create table UIM_InstantiationComponent (id number(19,0) not null, UIMClassName varchar2(3000), ManagedElementType varchar2(3000), Package varchar2(3000), Autonomous number(1,0), ProviderClassName varchar2(3000), primary key (id));
create table UIM_LogicalDevice (id number(19,0) not null, primary key (id));
create table UIM_LogicalElement (id number(19,0) not null, primary key (id));
create table UIM_ManagedElement (id number(19,0) not null, discriminator_type varchar2(255 char) not null, Caption varchar2(3000), Description varchar2(3000), DisplayName varchar2(3000), DeletionAllowed number(1,0), MonitoringStatus number(5,0), class_type varchar2(255 char), namespace_path varchar2(255 char), primary key (id));
create table UIM_ManagedSystemElement (id number(19,0) not null, ElementType varchar2(3000), Name varchar2(3000), OperationalStatus_value varchar2(4000 char), OperationalStatus_value_type number(10,0), MaintenanceOutageAllowed number(1,0), SystemId number(19,0), primary key (id));
create table UIM_ManagementInterface (id number(19,0) not null, Name varchar2(3000), primary key (id));
create table UIM_MonitoringInterface (id number(19,0) not null, Name varchar2(3000), Status number(5,0), AutoStart number(1,0), IPAddress varchar2(3000), Version varchar2(3000), primary key (id));
create table UIM_NetworkElement (id number(19,0) not null, IPAddress varchar2(3000), ManagementStatus number(5,0), primary key (id));
create table UIM_NetworkResourceInstantiati (id number(19,0) not null, ManagementAgentName varchar2(3000), primary key (id));
create table UIM_PhysicalElement (id number(19,0) not null, primary key (id));
create table UIM_Port (id number(19,0) not null, TrafficType varchar2(3000), MediaType varchar2(3000), MaxOutboundLinks number(19,0), MaxInboundLinks number(19,0), OutboundConnections number(19,0), InboundConnections number(19,0), primary key (id));
create table UIM_SNMPDeviceInstComponent (id number(19,0) not null, AlarmSleep number(19,0), AttributeSleep number(19,0), ConfigurationSleep number(19,0), SnmpSleepTimeout number(10,0), SnmpWriteCommunity varchar2(3000), SnmpVersion number(10,0), SnmpTimeout number(19,0), SnmpRetries number(10,0), SnmpReadCommunity varchar2(3000), SnmpMaxSessions number(10,0), SnmpTrapPort varchar2(3000), SnmpDevicePort varchar2(3000), SnmpDeviceIP varchar2(3000), SnmpAuthPassPhrase varchar2(3000), SnmpAuthProtocol varchar2(3000), SnmpContextEngineID varchar2(3000), SnmpContextName varchar2(3000), SnmpPrivPassPhrase varchar2(3000), SnmpPrivProtocol varchar2(3000), SnmpSecurityLevel number(10,0), SnmpSecurityName varchar2(3000), SnmpMaxRepetitions number(10,0), SnmpNonRepeaters number(10,0), primary key (id));
create table UIM_SNMPDeviceMgmtInterface (id number(19,0) not null, primary key (id));
create table UIM_SNMPDeviceMonInterface (id number(19,0) not null, AlarmSleep number(19,0), AttributeSleep number(19,0), CheckConnectivityMethod number(10,0), ConfigurationSleep number(19,0), IcmpRetries number(10,0), IcmpTimeout number(19,0), SnmpWriteCommunity varchar2(3000), SnmpVersion number(10,0), SnmpTimeout number(19,0), SnmpRetries number(10,0), SnmpReadCommunity varchar2(3000), SnmpMaxSessions number(10,0), SnmpTrapPort varchar2(3000), SnmpDevicePort varchar2(3000), SnmpAuthPassPhrase varchar2(3000), SnmpAuthProtocol varchar2(3000), SnmpContextEngineID varchar2(3000), SnmpContextName varchar2(3000), SnmpPrivPassPhrase varchar2(3000), SnmpPrivProtocol varchar2(3000), SnmpSecurityLevel number(10,0), SnmpSecurityName varchar2(3000), SnmpMaxRepetitions number(10,0), SnmpNonRepeaters number(10,0), PollingCyclesNames_value varchar2(4000 char), PollingCyclesNames_value_type number(10,0), PollingCyclesIntervals_value varchar2(4000 char), PollingCyclesInterv_value_type number(10,0), primary key (id));
alter table CIM_EnabledLogicalElement add constraint FK816CE9C9F1286E5 foreign key (id) references CIM_ManagedElement;
alter table CIM_LogicalElement add constraint FKC048A16B18E71B18 foreign key (id) references CIM_ManagedElement;
create index index_1441058333758_owningName on CIM_ManagedElement (namespace_path);
alter table CIM_ManagedSystemElement add constraint FK95278526CB92C953 foreign key (id) references CIM_ManagedElement;
create index index_1441058334696_SystemName on CIM_Service (SystemName);
create index index_1441058334696_SystemCrea on CIM_Service (SystemCreationClassName);
create index index_1441058334696_CreationCl on CIM_Service (CreationClassName);
alter table CIM_Service add constraint FK9F6D72FDA87C33C6 foreign key (id) references CIM_ManagedElement;
alter table CIM_WBEMService add constraint FK285152EADE628CB3 foreign key (id) references CIM_ManagedElement;
alter table HNSD_GDEpriT861Provider add constraint FK9CD16B7A875C280 foreign key (id) references CIM_ManagedElement;
alter table HNSD_GenericAgentProvider add constraint FK147BB507AB776D50 foreign key (id) references CIM_ManagedElement;
alter table HNSD_GenericProvider add constraint FKDA25166084DAB38D foreign key (id) references CIM_ManagedElement;
alter table HNSD_Provider add constraint FK6505D379653660C2 foreign key (id) references CIM_ManagedElement;
create index index_1416524119248_Version on UIM_AutonomousDeviceInstantiat (Version);
alter table UIM_AutonomousDeviceInstantiat add constraint FKC9E8D347C7D7B249 foreign key (id) references UIM_ManagedElement;
alter table UIM_AutonomousNetworkResourceI add constraint FK3C4ECAE33D3FB6BF foreign key (id) references UIM_ManagedElement;
alter table UIM_GDEpriT861EthernetGrouping add constraint FK282B291ED14157CB foreign key (id) references UIM_ManagedElement;
alter table UIM_GDEpriT861EthernetPort add constraint FK42796A1C8AF331C9 foreign key (id) references UIM_ManagedElement;
alter table UIM_GDEpriT861InstComponent add constraint FK201AD8B3E6D87D7C foreign key (id) references UIM_ManagedElement;
alter table UIM_GDEpriT861MgmtInterface add constraint FK98558CD45F13319D foreign key (id) references UIM_ManagedElement;
alter table UIM_GDEpriT861MonInterface add constraint FKB799E4B113AC5E foreign key (id) references UIM_ManagedElement;
alter table UIM_GDEpriT861NetworkElement add constraint FKB1BE4512C2B3B03F foreign key (id) references UIM_ManagedElement;
alter table UIM_GDEpriT861Port add constraint FK4C70CDA5A50F4752 foreign key (id) references UIM_ManagedElement;
alter table UIM_GDEpriT861Vlans add constraint FK41FBD6CCFD2B0995 foreign key (id) references UIM_ManagedElement;
alter table UIM_GDEpriT861VlansGrouping add constraint FK94574BEF5B14F0B8 foreign key (id) references UIM_ManagedElement;
alter table UIM_GenericAgentMonInterface add constraint FK9C997B81AD8EE6AE foreign key (id) references UIM_ManagedElement;
alter table UIM_GenericDeviceInstComponent add constraint FK5B846B3049A99DD foreign key (id) references UIM_ManagedElement;
alter table UIM_GenericDeviceMonInterface add constraint FK3DA58E944B5BFFDD foreign key (id) references UIM_ManagedElement;
alter table UIM_GenericGrouping add constraint FKD59A07D490C93A9D foreign key (id) references UIM_ManagedElement;
alter table UIM_GenericLogicalDevice add constraint FK6F66B8E3D61AFBB foreign key (id) references UIM_ManagedElement;
alter table UIM_GenericNetworkElement add constraint FKF70176FF8DFD2F48 foreign key (id) references UIM_ManagedElement;
alter table UIM_GenericPort add constraint FK7B6013D231714D9B foreign key (id) references UIM_ManagedElement;
alter table UIM_GenericSNMPDeviceMonInterf add constraint FKD0510F11CF566E1B foreign key (id) references UIM_ManagedElement;
create index index_1441058335184_ManagedEle on UIM_InstantiationComponent (ManagedElementType);
create index index_1441058335184_UIMClassNa on UIM_InstantiationComponent (UIMClassName);
alter table UIM_InstantiationComponent add constraint FK58EB6916A16530C3 foreign key (id) references UIM_ManagedElement;
alter table UIM_LogicalDevice add constraint FKB015AE19268E7462 foreign key (id) references UIM_ManagedElement;
alter table UIM_LogicalElement add constraint FK928A8799EB290146 foreign key (id) references UIM_ManagedElement;
create index index_1441058335170_owningName on UIM_ManagedElement (namespace_path);
create index index_1441058335175_Name on UIM_ManagedSystemElement (Name);
alter table UIM_ManagedSystemElement add constraint FK4D4390D483AED501 foreign key (id) references UIM_ManagedElement;
create index index_1441058335183_Name on UIM_ManagementInterface (Name);
alter table UIM_ManagementInterface add constraint FK520EF710F0B7A2D9 foreign key (id) references UIM_ManagedElement;
create index index_1441058335191_Name on UIM_MonitoringInterface (Name);
alter table UIM_MonitoringInterface add constraint FKE10180AB7FAA2C74 foreign key (id) references UIM_ManagedElement;
alter table UIM_NetworkElement add constraint FK71CA85D4CA68FF81 foreign key (id) references UIM_ManagedElement;
alter table UIM_NetworkResourceInstantiati add constraint FK2665D4D8D4D62A4F foreign key (id) references UIM_ManagedElement;
alter table UIM_PhysicalElement add constraint FKE20849FF9D377CC8 foreign key (id) references UIM_ManagedElement;
alter table UIM_Port add constraint FK1C30B8E7CB406114 foreign key (id) references UIM_ManagedElement;
alter table UIM_SNMPDeviceInstComponent add constraint FKD568AE7D9C265346 foreign key (id) references UIM_ManagedElement;
alter table UIM_SNMPDeviceMgmtInterface add constraint FK4DA3629E14610767 foreign key (id) references UIM_ManagedElement;
alter table UIM_SNMPDeviceMonInterface add constraint FKC5B52DA7E2EF554 foreign key (id) references UIM_ManagedElement;
create sequence total_instance_sequence;
